### ISSUE TITLE
Fetching hit sequences from remote db is pretty slow.

### ISSUE THREAD

**Issue by yeban** [wurmlab/genevalidator#102]
I think the issue is that sequences are fetched one at a time - https://github.com/wurmlab/genevalidator/blob/master/lib/genevalidator/get_raw_sequences.rb#L96

Can this be speeded-up by fetching raw sequences all at once or 50 at a time maybe?

**Comment by yannickwurm** [comment]
not worth the effort - people should use local db for more queries

**Comment by yeban** [comment]
It's slow even for just 10 sequences.
