### ISSUE TITLE
Shouldn't the columns expected by -t & -o be documented?

### ISSUE THREAD

**Issue by yeban** [wurmlab/genevalidator#105]
These are the ones picked by GV -  `qstart qend qframe sstart send qseq sseq length pident nident evalue sseqid sacc slen`. The test data though additionally includes `qseqid` (in the following order - `qseqid sseqid sacc slen qstart qend sstart send length qframe pident nident evalue qseq sseq`).

**Comment by IsmailM** [comment]
We use `qseqid` [here](https://github.com/wurmlab/genevalidator/blob/master/lib/genevalidator/tabular_parser.rb#L47)...

The Readme does show the recommended `-outfmt` option [here](https://github.com/wurmlab/genevalidator/blob/master/README.md#running-blast-separately)

Is that enough or do you think we should explicitly document this?

**Comment by yeban** [comment]
Sorry, I was looking in the `-h` output.
