### ISSUE TITLE
Option to skip based on regexp

### ISSUE THREAD

**Issue by yannickwurm** [wurmlab/genevalidator#12]
Currently, hits that are identical to the query sequence are skipped. 

This may be insufficient: indeed if I am trying to improve a gene in a genome for which there is already (approximate) data in a public database, I will likely want to skip all the information from this species. Thus an option to filter hits (based e.g. on regexp matching) would be very helpful. I would likely want to use /Solenopsis|13686/ as an exclusion filter on the sequence ID/description (13686 is NCBI taxonomy's ID for Solenopsis invicta.

**Comment by IsmailM** [comment]
Is it possible to run BLAST while skipping based on an exclusion filter?

**Comment by yeban** [comment]
`-negative_gilist` is the only option. To skip taxid '13686' I think something like below would have to be done:

    blastdbcmd -db nr -entry all -outfmt '%g %T' | grep 13686 | awk '{print $1}' > 13686.gilist
    blastp -db nr -query query.fa -negative_gilist 13686.gilist

The first command can take a lot of time and memory to run. In my case this will effectively reduce db size and hence evalue, which probably is desireable.

... or filtering can be done by GV after BLAST as well.

**Comment by yannickwurm** [comment]
@yeban 's solution is indeed the best. If people have complex queries they should perform them outside of GV.
