### ISSUE TITLE
add more info on the blast database

### ISSUE THREAD

**Issue by estolle** [wurmlab/genevalidator#121]
Its was unclear to me what the protein blast database should comprise and where I would get a suitable selection of sequences. I think it would be very helpful to add a bit of info here. eg.

Download Uniprot.fasta and make a database yourself:

sudo wget  ftp://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/uniprot_sprot.fasta.gz
gunzip uniprot_sprot.fasta.gz
makeblastdb -in uniprot_sprot.fasta -dbtype 'prot' -parse_seqids -out swissprot

the downloaded NCBI's swissprot database somehow didnt work for genevalidator:  sudo wget ftp://ftp.ncbi.nlm.nih.gov/blast/db/swissprot.tar.gz

**Comment by IsmailM** [comment]
GV now includes the SwissProt Database when installing using the one-liner install command:

```bash
sh -c "$(curl -fsSL https://install-genevalidator.wurmlab.com)"
```

And the Readme now contains a link to [this Gist](https://gist.github.com/IsmailM/3e3519de18c5b8b36d8aa0f223fb7948) which contains more info on how to create BLAST dbs.

PS. also take a look at https://github.com/yeban/ncbi-blast-dbs
