### ISSUE TITLE
Genevalidator is still noting that I should install speadsheets gem to use this functionality

### ISSUE THREAD

**Issue by estolle** [wurmlab/genevalidator#122]
GV still says "Install the spreadsheet gem version ~>1.1.1 for using spreadsheet functions"
I did install it already (sudo gem install spreadsheet" --> v1.1.5

Is this a bug?

**Comment by IsmailM** [comment]
Hey @estolle,

Yes, this a bug from a downstream dependency (a dependency of a dependency). Feel free to add a +1 to the GitHub issue I raised there, over half a year ago - Sciruby/Daru#404.

However, It doesn't affect the functionality of GV at all (i.e. we don't use those libraries) - so please ignore it for now. I'm planning to move to away from this dependency in the next update so hopefully, this won't be an issue for much longer.

**Comment by estolle** [comment]
Cool, thanks alot Ismail!!
