### ISSUE TITLE
Help output should be written to stdout

### ISSUE THREAD

**Issue by yeban** [wurmlab/genevalidator#126]
To read GV's helpful output, stderr must be redirected to stdout: `genevalidator 2>&1 | less`.  GV's output is long, so people will need to use `less`. Not being able to "just pipe" will be a potential pain point.

**Comment by yeban** [comment]
(using `dev` branch)

**Comment by IsmailM** [comment]
do you mean the output of `genevalidator --help`?

**Comment by yeban** [comment]
That and when invoked without any options (`$ genevalidator`)
