### ISSUE TITLE
Number of hits with insufficient evidence

### ISSUE THREAD

**Issue by yeban** [wurmlab/genevalidator#129]
Looks like transcript sequences will always have 0 number of hits with insufficient evidence because of the ORF validation that does not require any hits. Here's an [example](http://antgenomes.org/~priyam/GV_2018_07_07_19_09_36). I think `num_hits_with_insufficient_blast_hits` might be more relevant.

**Comment by IsmailM** [comment]
Threshold BLAST hits = 5 and 10
