### ISSUE TITLE
Undefined method

### ISSUE THREAD

**Issue by MARS2280** [wurmlab/genevalidator#138]
Dear wurmlab

I have 3 genomes (1200 -1400 proteins), each annotated with prokka.
   
I followed your instructions but I have an issue. 
```bash
$ genevalidator  -d /home/mars/uniprotDB/uniprot_sprot.fasta -o c18b_S15_genevalidator c18b_S15_prokka/c18b_S15.faa

790	   45	      c18b_S15_00814	    365	439 [341, 378]	6% (too long)	-13.1	1.0	100% conserved; 100% extra; 0% missing.
791	   64	      c18b_S15_00815	    499	347 [347, 360]	19% (too short)	-2.6	1.0	100% conserved; 100% extra; 0% missing.
792	   45	      c18b_S15_00816	    498	886 [871, 885]	14% (too long)	0.0	1.0	100% conserved; 100% extra; 0% missing.
/home/mars/Programs/genevalidator/lib/vendor/ruby/2.2.0/gems/genevalidator-2.1.5/lib/genevalidator/validation.rb:75:in `get_info_on_query_sequence': undefined method `[]' for nil:NilClass (NoMethodError)
	from /home/mars/Programs/genevalidator/lib/vendor/ruby/2.2.0/gems/genevalidator-2.1.5/lib/genevalidator/validation.rb:42:in `run_validations'
	from /home/mars/Programs/genevalidator/lib/vendor/ruby/2.2.0/gems/genevalidator-2.1.5/lib/genevalidator.rb:58:in `run'
	from /home/mars/Programs/genevalidator/bin/../lib/app/bin/genevalidator:357:in `<main>'
```
As you could see, the analysis finished in the 792 number protein. 
What am I doing wrong? Could you help me, please? 

Thank in advance!

**Comment by IsmailM** [comment]
Hi, 

Sorry to hear that you are having issues with GV.

It seems that there are issues with parsing the FASTA sequence of the 793rd sequence. Do you mind uploading the relevant part of the fasta here (instructions below)? Alternatively, you can send me the fasta file via email (ismail.moghul@gmail.com) and I can have a look at it.

Once we get to the root of the issue, you should be able to resume the analysis (using the failed directory name) as follows:

```
genevalidator --db 'home/mars/uniprotDB/uniprot_sprot.fasta' --resume 'c18b_S15_genevalidator' --output_dir 'c18b_S15_genevalidator_1'  c18b_S15_prokka/c18b_S15.faa
```

Kind regards,
Ismail Moghul


To extract sequences 790-800 from the FASTA file:

```bash
# Requires prior [Samtools installation](www.htslib.org/) 
samtools faidx c18b_S15_prokka/c18b_S15.faa
# This creates a index file c18b_S15_prokka/c18b_S15.faa.fai

# Next we use sed to get lines 790 to 800 of the index file
# We pass this to cut to extract the sequence id
# which we then pass to xargs samtools faidx to extract the relevant sequences 

sed -n '790,800p' c18b_S15_prokka/c18b_S15.faa.fai | \
  cut -f 1 | \
  xargs samtools faidx c18b_S15_prokka/c18b_S15.faa > c18b_S15_subset.faa

```

**Comment by IsmailM** [comment]
Hi Manuel,

Thank you for sharing the exemplar dataset. This helped in identifying a bug in GeneValidator in parsing the input FASTA file - specifically in the case where the sequence definition contained more than one `>`.

We have now released a fix to this issue. You can install the updated GeneValidator version as follows:

```bash 
# Installs in a folder called `genevalidator` in your current folder
sh -c "$(curl -fsSL https://install-genevalidator.wurmlab.com)"

# Close 
# check version - should be 2.1.9
genevalidator --version

# in your project folder, rerun GV
# using `-r -f` flags to resume the analysis.
genevalidator -d /home/mars/uniprotDB/uniprot_sprot.fasta -r -f -o c18b_S15_genevalidator c18b_S15_prokka/c18b_S15.faa
```

(You can remove the old GV installation by simply deleting the old installation folder)

Feel free to reopen this issue if this doesn't fix the issue for you.

Kind Regards, 
Ismail Moghul
