### ISSUE TITLE
Length visualisation has a bug?

### ISSUE THREAD

**Issue by yeban** [wurmlab/genevalidator#143]
Attached query file against uniref50 (downloaded 2nd Oct, 2018) - 
[predictions.txt](https://github.com/wurmlab/genevalidator/files/2441300/predictions.txt)

First query has length 806, but the length vis shows a different length - 
<img width="609" alt="screen shot 2018-10-03 at 09 49 25" src="https://user-images.githubusercontent.com/90373/46400313-04d12200-c6f2-11e8-8aa0-949fe0290ee7.png">

**Comment by IsmailM** [comment]
Seems to work fine for me with the latest version of GV (with both SwissProt and Uniref50 that was downloaded today)...


###### Uniref50 

<img width="1281" alt="genevalidator__identify_problems_with_gene_predictions" src="https://user-images.githubusercontent.com/5578375/46435606-a2f2d580-c74e-11e8-8b89-20241c4869ae.png">


###### SwissProt

<img width="1266" alt="genevalidator__identify_problems_with_gene_predictions" src="https://user-images.githubusercontent.com/5578375/46435649-c3229480-c74e-11e8-803a-9dff9e7f5737.png">





- How did you produce those results ?
- Secondly if it's still issue, please share the output folder.

**Comment by yeban** [comment]
> How did you produce those results ?

Using `-x` option. Had the BLAST output already.

```
bundle exec bin/genevalidator -x msc/limited_hits.xml -d ~/uniref50/uniref50.fasta -o msc/limited_hits msc/query.fa
```

> Secondly if it's still issue, please share the output folder.

Here - [msc.tar.gz](https://github.com/wurmlab/genevalidator/files/2446754/msc.tar.gz). Contains query fasta, BLAST xml, GV output.

**Comment by IsmailM** [comment]
Seems to be working fine for me. (Moreover, the example you showed above is not included in the tarball).

- what browser are you using (can you try using a different browser)?
- Anything in the JS console.

**Comment by IsmailM** [comment]
This seems to be due to the fact that the input file had windows line endings (`\r\n`) and we assumed UNIX line endings (`\n`).

Will submit a new release with this fix soon.
