### ISSUE TITLE
genevalidator standalone

### ISSUE THREAD

**Issue by estolle** [wurmlab/genevalidator#147]
Hi there

I tried to DL the standalone version of GV for which it saxs "Simply download, uncompress and start validating your genes with GeneValidator". 

If I link the executable and start it i get this error:
/usr/local/bin/genevalidator: line 19: /usr/local/bin/lib/ruby/bin/ruby: No such file or directory

If i run it like this ./genevalidator while being in the install folder then I get this (could be resolved by changing the owner of the DIR from root to myself):
There was an error while trying to write to Gemfile.lock. It is likely that 
you need to allow write permissions for the file at path: 
/opt/genevalidator-2.1.9-linux-x86_64/lib/vendor/Gemfile.lock

Starting it then using "/opt/genevalidator-2.1.9-linux-x86_64/genevalidator"  seems to work but starting it by calling a symlink does not. 
/usr/local/bin/genevalidator: line 19: /usr/local/bin/lib/ruby/bin/ruby: No such file or directory

I can run it using the entire path to the executable but is there a way to make symlinking work?

Thanks
Eckart

**Comment by estolle** [comment]
Hi Ismail

Thanks for quick reply. I was aiming to install GV systemwide, ie not in my HOME DIR, using the script and adding it to my profile only partially would work. Hence my question. 
I guess "add the GV bin folder to your PATH" answers my Question - I can add it to the ENV.

Cheers!

**Comment by IsmailM** [comment]
No worries, glad I could help.
