### ISSUE TITLE
NoMethodError - undefined method `+' for nil:NilClass

### ISSUE THREAD

**Issue by rlebron-bioinfo** [wurmlab/genevalidator#160]
Dear Wurm Lab,

First of all, thank you for creating and maintaining _genevalidator_.  I'm having issues with both the web app and the local installation of _genevalidator_ and this is the error that keeps happening:

> ==> Extracting fasta sequences for each BLAST HSP from the BLAST database
> 2021-06-08 17:07:23 - NoMethodError - undefined method `+' for nil:NilClass:
> 	/Users/rlebron/genevalidator/lib/vendor/ruby/2.2.0/gems/genevalidator-2.1.10/lib/genevalidator/ext/array.rb:15:in `median'
> 	/Users/rlebron/genevalidator/lib/vendor/ruby/2.2.0/gems/genevalidator-2.1.10/lib/genevalidator/ext/array.rb:40:in `all_quartiles'
> 	/Users/rlebron/genevalidator/lib/vendor/ruby/2.2.0/gems/genevalidator-2.1.10/lib/genevalidator/output.rb:113:in `generate_overview'
> 	/Users/rlebron/genevalidator/lib/vendor/ruby/2.2.0/gems/genevalidator-2.1.10/lib/genevalidator.rb:101:in `produce_output'
> 	/Users/rlebron/genevalidator/lib/vendor/ruby/2.2.0/gems/genevalidator-2.1.10/lib/genevalidator.rb:59:in `run'
> 	/Users/rlebron/genevalidator/lib/vendor/ruby/2.2.0/gems/genevalidatorapp-2.1.8/lib/genevalidatorapp/genevalidator.rb:172:in `run_gv'
> 	/Users/rlebron/genevalidator/lib/vendor/ruby/2.2.0/gems/genevalidatorapp-2.1.8/lib/genevalidatorapp/genevalidator.rb:163:in `run_genevalidator'
> 	/Users/rlebron/genevalidator/lib/vendor/ruby/2.2.0/gems/genevalidatorapp-2.1.8/lib/genevalidatorapp/genevalidator.rb:46:in `run'
> 	/Users/rlebron/genevalidator/lib/vendor/ruby/2.2.0/gems/genevalidatorapp-2.1.8/lib/genevalidatorapp/routes.rb:96:in `block in <class:Routes>'
> 	/Users/rlebron/genevalidator/lib/vendor/ruby/2.2.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1636:in `call'
> 	/Users/rlebron/genevalidator/lib/vendor/ruby/2.2.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1636:in `block in compile!'
> 	/Users/rlebron/genevalidator/lib/vendor/ruby/2.2.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:987:in `[]'
> 	/Users/rlebron/genevalidator/lib/vendor/ruby/2.2.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:987:in `block (3 levels) in route!'
> 	/Users/rlebron/genevalidator/lib/vendor/ruby/2.2.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1006:in `route_eval'
> 	/Users/rlebron/genevalidator/lib/vendor/ruby/2.2.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:987:in `block (2 levels) in route!'
> 	/Users/rlebron/genevalidator/lib/vendor/ruby/2.2.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1035:in `block in process_route'
> 	/Users/rlebron/genevalidator/lib/vendor/ruby/2.2.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1033:in `catch'
> 	/Users/rlebron/genevalidator/lib/vendor/ruby/2.2.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1033:in `process_route'
> 	/Users/rlebron/genevalidator/lib/vendor/ruby/2.2.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:985:in `block in route!'
> 	/Users/rlebron/genevalidator/lib/vendor/ruby/2.2.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:984:in `each'
> 	/Users/rlebron/genevalidator/lib/vendor/ruby/2.2.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:984:in `route!'
> 	/Users/rlebron/genevalidator/lib/vendor/ruby/2.2.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1098:in `block in dispatch!'
> 	/Users/rlebron/genevalidator/lib/vendor/ruby/2.2.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `block in invoke'
> 	/Users/rlebron/genevalidator/lib/vendor/ruby/2.2.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `catch'
> 	/Users/rlebron/genevalidator/lib/vendor/ruby/2.2.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `invoke'
> 	/Users/rlebron/genevalidator/lib/vendor/ruby/2.2.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1095:in `dispatch!'
> 	/Users/rlebron/genevalidator/lib/vendor/ruby/2.2.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:919:in `block in call!'
> 	/Users/rlebron/genevalidator/lib/vendor/ruby/2.2.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `block in invoke'
> 	/Users/rlebron/genevalidator/lib/vendor/ruby/2.2.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `catch'
> 	/Users/rlebron/genevalidator/lib/vendor/ruby/2.2.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `invoke'
> 	/Users/rlebron/genevalidator/lib/vendor/ruby/2.2.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:919:in `call!'
> 	/Users/rlebron/genevalidator/lib/vendor/ruby/2.2.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:908:in `call'
> 	/Users/rlebron/genevalidator/lib/vendor/ruby/2.2.0/gems/rack-protection-2.0.8.1/lib/rack/protection/xss_header.rb:18:in `call'
> 	/Users/rlebron/genevalidator/lib/vendor/ruby/2.2.0/gems/rack-protection-2.0.8.1/lib/rack/protection/path_traversal.rb:16:in `call'
> 	/Users/rlebron/genevalidator/lib/vendor/ruby/2.2.0/gems/rack-protection-2.0.8.1/lib/rack/protection/json_csrf.rb:26:in `call'
> 	/Users/rlebron/genevalidator/lib/vendor/ruby/2.2.0/gems/rack-protection-2.0.8.1/lib/rack/protection/base.rb:50:in `call'
> 	/Users/rlebron/genevalidator/lib/vendor/ruby/2.2.0/gems/rack-protection-2.0.8.1/lib/rack/protection/base.rb:50:in `call'
> 	/Users/rlebron/genevalidator/lib/vendor/ruby/2.2.0/gems/rack-protection-2.0.8.1/lib/rack/protection/frame_options.rb:31:in `call'
> 	/Users/rlebron/genevalidator/lib/vendor/ruby/2.2.0/gems/rack-2.1.4/lib/rack/head.rb:14:in `call'
> 	/Users/rlebron/genevalidator/lib/vendor/ruby/2.2.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:194:in `call'
> 	/Users/rlebron/genevalidator/lib/vendor/ruby/2.2.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1951:in `call'
> 	/Users/rlebron/genevalidator/lib/vendor/ruby/2.2.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1503:in `block in call'
> 	/Users/rlebron/genevalidator/lib/vendor/ruby/2.2.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1730:in `synchronize'
> 	/Users/rlebron/genevalidator/lib/vendor/ruby/2.2.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1503:in `call'
> 	/Users/rlebron/genevalidator/lib/vendor/ruby/2.2.0/gems/genevalidatorapp-2.1.8/lib/genevalidatorapp.rb:92:in `call'
> 	/Users/rlebron/genevalidator/lib/vendor/ruby/2.2.0/gems/rack-2.1.4/lib/rack/handler/webrick.rb:88:in `service'
> 	/Users/rlebron/genevalidator/lib/ruby/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
> 	/Users/rlebron/genevalidator/lib/ruby/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
> 	/Users/rlebron/genevalidator/lib/ruby/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'

Could you please help me? Thank you very much.

Best regards,
Ricardo Lebrón

**Comment by IsmailM** [comment]
Hi Ricardo,

Sorry to hear you are having issues running GeneValidator.

Do you see the same issue with the exemplar data? e.g.

```bash
# After installing the latest version (2.1.10) via the automated install script
sh -c "$(curl -fsSL https://install-genevalidator.wurmlab.com)"

# move into the genevalidator folder
cd genevalidator

# Run GV in CLI mode with the exemplar data using 8 threads
genevalidator -n 8 -d blast_db/swissprot exemplar_data/protein_data.fa
genevalidator -n 8 -d blast_db/swissprot exemplar_data/mrna_data.fa

# Run GV in app mode using 8 threads
genevalidator app -n 8

# click on the 'Show a protein/DNA example' buttons
```

If the above works for you, can you provide us with the following details:

1. what is the version of the GV used? (`genevalidator --version`)

2. How did you install GV? Through the automated install script (as above) or otherwise?

3. What was the exact command you ran?

4. Would it be possible to share some exemplar data that failed?
    * Feel free to email me this directly at `ucbtmog <at> ucl.ac.uk` if you cannot upload the data here.

**Comment by rlebron-bioinfo** [comment]
Hi Ismail,

Thank you for your quick response. It is not only my installation, it happens even with your own web application (https://genevalidator.wurmlab.com/). With the example data, your web application does not fail (maybe the results are pre-calculated?), but however with any other protein I have tried it fails, for example:

> >sp|Q9UKV8|AGO2_HUMAN Protein argonaute-2 OS=Homo sapiens OX=9606 GN=AGO2 PE=1 SV=3
> MYSGAGPALAPPAPPPPIQGYAFKPPPRPDFGTSGRTIKLQANFFEMDIPKIDIYHYELD
> IKPEKCPRRVNREIVEHMVQHFKTQIFGDRKPVFDGRKNLYTAMPLPIGRDKVELEVTLP
> GEGKDRIFKVSIKWVSCVSLQALHDALSGRLPSVPFETIQALDVVMRHLPSMRYTPVGRS
> FFTASEGCSNPLGGGREVWFGFHQSVRPSLWKMMLNIDVSATAFYKAQPVIEFVCEVLDF
> KSIEEQQKPLTDSQRVKFTKEIKGLKVEITHCGQMKRKYRVCNVTRRPASHQTFPLQQES
> GQTVECTVAQYFKDRHKLVLRYPHLPCLQVGQEQKHTYLPLEVCNIVAGQRCIKKLTDNQ
> TSTMIRATARSAPDRQEEISKLMRSASFNTDPYVREFGIMVKDEMTDVTGRVLQPPSILY
> GGRNKAIATPVQGVWDMRNKQFHTGIEIKVWAIACFAPQRQCTEVHLKSFTEQLRKISRD
> AGMPIQGQPCFCKYAQGADSVEPMFRHLKNTYAGLQLVVVILPGKTPVYAEVKRVGDTVL
> GMATQCVQMKNVQRTTPQTLSNLCLKINVKLGGVNNILLPQGRPPVFQQPVIFLGADVTH
> PPAGDGKKPSIAAVVGSMDAHPNRYCATVRVQQHRQEIIQDLAAMVRELLIQFYKSTRFK
> PTRIIFYRDGVSEGQFQQVLHHELLAIREACIKLEKDYQPGITFIVVQKRHHTRLFCTDK
> NERVGKSGNIPAGTTVDTKITHPTEFDFYLCSHAGIQGTSRPSHYHVLWDDNRFSSDELQ
> ILTYQLCHTYVRCTRSVSIPAPAYYAHLVAFRARYHLVDKEHDSAEGSHTSGQSNGRDHQ
> ALAKAVQVHQDTLRTMYFA

![Captura de pantalla 2021-06-10 a las 9 08 19](https://user-images.githubusercontent.com/46110571/121480758-b65ca100-c9cb-11eb-847b-a9f1065c361d.png)

Even your docker container from 4 years ago fails (https://hub.docker.com/r/wurmlab/genevalidatorapp). However, this other docker container works perfectly: https://hub.docker.com/r/joharohl/genevalidatorapp-uniprot . It seems to be a Ruby problem.

> Do you see the same issue with the exemplar data? e.g.

The example data works on my local installation, but every other dataset I have tried fails.

> 1. What is the version of the GV used? (genevalidator --version)

2.1.10

> 2. How did you install GV? Through the automated install script (as above) or otherwise?

Through the automated install script (as above).

> 3. What was the exact command you ran?
> 4. Would it be possible to share some exemplar data that failed?

`genevalidator -n 4 -d blast_db/swissprot mysequences.fa` (e.g. using the above sequence)

Best regards,
Ricardo Lebrón

**Comment by IsmailM** [comment]
Hi Ricardo,

Many thanks for the exemplar sequence.

I am able to reproduce the bug with this sequence.

As such, I will look into releasing a fix and will get back to you at the earliest.

Many thanks,
Ismail Moghul

**Comment by rlebron-bioinfo** [comment]
Hi Ismail,

Many thanks in advance.

Regards,
Ricardo Lebrón

**Comment by IsmailM** [comment]
Hi Ricardo,

I have released a fix for this issue (which was only affecting analyses consisting of a single sequence).

You will need to rerun the install script to install the latest version of GeneValidator (v: 2.1.11).

```bash
sh -c "$(curl -fsSL https://install-genevalidator.wurmlab.com)"
```

The demo server has not yet been updated - but I hope this will be done soon (cc: @yeban).

Hope this fixes everything for you - please do not hesitate in reaching out if you have any further questions/ issues.

**Comment by rlebron-bioinfo** [comment]
Hi Ismail,

Thank you, now everything is working for me.

By the way, I found a typo in the README:

`genevalidator app --database_dir genevalidator/blastdb --num_threads 4`

An underscore is missing in the default database path. It should look like this:

`genevalidator app --database_dir genevalidator/blast_db --num_threads 4`

Best regards,
Ricardo Lebrón

**Comment by IsmailM** [comment]
Good catch on the typo 👍  - I'll fix that right away.

**Comment by yeban** [comment]
> The demo server has not yet been updated - but I hope this will be done soon

Done!
