### ISSUE TITLE
Missing Extra Sequences Validation not working

### ISSUE THREAD

**Issue by jwinternitz** [wurmlab/genevalidator#168]
Hi,
I seem to be having an issue with the Missing Extra Sequences Validation step. I only get the same result for any file I use: "100% conserved; 100% extra; 0% missing." The graph using the local host in my browser is also empty, with no results for hit 1-10. I installed the currently available program from github using the command provided in the installation example. I used the example protein_data.fa with the following code:

genevalidator -d genevalidator/blast_db/swissprot genevalidator/exemplar_data/protein_data.fa --
output_dir genevalidator.out
==> Analysing input arguments

==> Running BLAST. This may take a while.

==> Extracting fasta sequences for each BLAST HSP from the BLAST database
==> Validating input sequences

 No     Score             Identifier    No_Hits LengthCluster   LengthRank      GeneMerge       Duplication     MissingExtraSequences
  1        67             GB10056-PA         10 339 [317, 365]  40%     -3.5    1.0     100% conserved; 100% extra; 0% missing.
  2        67             GB10063-PA        324 615 [105, 668]  42%     0.0     1.0     100% conserved; 100% extra; 0% missing.
  3        64             GB10113-PA         19 659 [300, 506]  37%     -2.4    0.25    100% conserved; 100% extra; 0% missing.
  4        64          SI2.2.0_02565         18 1761 [1603, 1677]       50%     -0.1    1.0     100% conserved; 100% extra; 0% missing.
  5        67             PB18768-RA          7 132 [124, 137]  43%     0.0     1.0     Not enough evidence
  6        64          SI2.2.0_02651         34 660 [404, 1242] 15% (too short) 0.0     1.0     100% conserved; 100% extra; 0% missing.
  7        45             PB11933-RA         52 845 [667, 885]  37%     1.1     1.0     100% conserved; 100% extra; 0% missing.
  8        45             PB13758-RA        176 751 [763, 1531] 3% (too short)  0.0     1.0     100% conserved; 100% extra; 0% missing.
  9        22             GB10071-PA         27 494 [379, 402]  0% (too long)   -7.0    0.0     100% conserved; 100% extra; 0% missing.
 10         0             PB26730-RA          0 Not enough evidence     Not enough evidence     Not enough evidence     Not enough evidence  Not enough evidence

![Uploading Screenshot 2023-06-13 225044.png…]()

For some reason the alignment is failing, but I don't know why and can't find a log file to try to understand the issue. This error in validation makes every sequence I test go into the category "possibly weak predictions". Any ideas how to fix this? 

Thanks,
Jamie

**Comment by jwinternitz** [comment]
I think the issue is with mafft. When I ran the protein_data.blast_xml.raw_seq from the /output/temp/ folder from the mafft/bin directory, mafft failed unless I added "--anysymbol" because some of the downloaded fasta sequences from the UniProt/SwissProt blast database had "U"s, which mafft needed to be told to recognize. Could this be the issue? If so, how would I tell genevalidator to use this option when running mafft?

**Comment by IsmailM** [comment]
Hi Jamie,

Apologies for the delay in getting back to you.

I have just tried a clean install of GeneValidator (using the single line install command) on a clean machine - and I do not see the same issue:

```bash
# Install GeneValidator
sh -c "$(curl -fsSL https://raw.githubusercontent.com/wurmlab/genevalidator/master/install.sh)"

cd genevalidator

# Run GeneValidator with the exemplar data using the included copy of SwissProt 
./genevalidator -d blast_db/swissprot exemplar_data/protein_data.fa
```

This gives the following output:

```bash
==> Analysing input arguments

==> Running BLAST. This may take a while.

==> Extracting fasta sequences for each BLAST HSP from the BLAST database
==> Validating input sequences

 No	Score	          Identifier	No_Hits	LengthCluster	LengthRank	GeneMerge	Duplication	MissingExtraSequences
  1	   90	          GB10056-PA	     10	339 [317, 365]	40%	-3.5	1.0	95% conserved; 2% extra; 11% missing.
  2	   90	          GB10063-PA	    324	615 [105, 668]	42%	0.0	1.0	97% conserved; 5% extra; 5% missing.
  3	   90	          GB10113-PA	     19	659 [300, 506]	37%	-2.4	0.25	100% conserved; 17% extra; 6% missing.
  4	   90	       SI2.2.0_02565	     18	1761 [1603, 1677]	50%	-0.1	1.0	100% conserved; 0% extra; 6% missing.
  5	   67	          PB18768-RA	      7	132 [124, 137]	43%	0.0	1.0	Not enough evidence
  6	   64	       SI2.2.0_02651	     34	660 [404, 1242]	15% (too short)	0.0	1.0	94% conserved; 2% extra; 21% missing.
  7	   45	          PB11933-RA	     52	845 [667, 885]	37%	1.1	1.0	86% conserved; 1% extra; 22% missing.
  8	   45	          PB13758-RA	    176	751 [763, 1531]	3% (too short)	0.0	1.0	81% conserved; 0% extra; 25% missing.
  9	   22	          GB10071-PA	     27	494 [379, 402]	0% (too long)	-7.0	0.0	79% conserved; 21% extra; 6% missing.
 10	    0	          PB26730-RA	      0	Not enough evidence	Not enough evidence	Not enough evidence	Not enough evidence	Not enough evidence

==> Overall Query Score Evaluation:
10 predictions were validated, from which there were:
4 are good prediction(s),
6 are possibly weak prediction(s).
1 prediction was not evaluated due to an insufficient number of BLAST hits.
The median overall score was 65.5 with an upper quartile of 90.0 and a lower quartile of 45.0.
Average running time for LengthCluster Validation: 0.009s per validation
Average running time for LengthRank Validation: 0.0s per validation
Average running time for GeneMerge Validation: 0.0s per validation
Average running time for Duplication Validation: 6.46s per validation
Average running time for MissingExtraSequences Validation: 2.052s per validation

==> GeneValidator output files have been saved to:
    /Users/ismailm/d/tmp/gv_install/protein_data_2023_06_19_08_46_35
Total running time: 106.324s
```

PS - we are using the `--anysymbol` argument for mafft - you can see this here:

https://github.com/wurmlab/genevalidator/blob/41a161410a0ac0da5d0f9f43755c0f5e885e9087/lib/genevalidator/validation_alignment.rb#L229-L230

and 

https://github.com/wurmlab/genevalidator/blob/41a161410a0ac0da5d0f9f43755c0f5e885e9087/lib/genevalidator/validation_duplication.rb#L214-L215

Can you provide a bit more information so we can work out why this is happening:

* What OS are you using.
* What is the version of GeneValidator that you used? (`genevalidator --version`)
* How did you install GeneValidator?
* What is the exact command that you ran?
* Do you have another copy of MAFFT / BLAST installed? 
* What is the output of `echo $PATH`?

**Comment by jwinternitz** [comment]
Hi Ismail,

thanks for your quick response! Here are my answers to your questions:

**## What OS are you using.**

(base) moonhartii@LAPTOP-SB1BDPOH:~$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy


**## What is the version of GeneValidator that you used? (genevalidator --version)**

(base) moonhartii@LAPTOP-SB1BDPOH:~$ genevalidator --version
2.1.11


**## How did you install GeneValidator?**

sh -c "$(curl -fsSL https://raw.githubusercontent.com/wurmlab/genevalidator/master/install.sh)"


**## What is the exact command that you ran?**

(base) moonhartii@LAPTOP-SB1BDPOH:~$ bash
(base) moonhartii@LAPTOP-SB1BDPOH:~$ genevalidator --db genevalidator/blast_db/swissprot genevalidator/exemplar_data/protein_data.fa
==> Analysing input arguments

==> Running BLAST. This may take a while.

==> Extracting fasta sequences for each BLAST HSP from the BLAST database
==> Validating input sequences

 No     Score             Identifier    No_Hits LengthCluster   LengthRank      GeneMerge       Duplication     MissingExtraSequences
  1        67             GB10056-PA         10 339 [317, 365]  40%     -3.5    1.0     100% conserved; 100% extra; 0% missing.
  2        67             GB10063-PA        324 615 [105, 668]  42%     0.0     1.0     100% conserved; 100% extra; 0% missing.
  3        64             GB10113-PA         19 659 [300, 506]  37%     -2.4    0.25    100% conserved; 100% extra; 0% missing.
  4        64          SI2.2.0_02565         18 1761 [1603, 1677]       50%     -0.1    1.0     100% conserved; 100% extra; 0% missing.
  5        67             PB18768-RA          7 132 [124, 137]  43%     0.0     1.0     Not enough evidence
  6        64          SI2.2.0_02651         34 660 [404, 1242] 15% (too short) 0.0     1.0     100% conserved; 100% extra; 0% missing.
  7        45             PB11933-RA         52 845 [667, 885]  37%     1.1     1.0     100% conserved; 100% extra; 0% missing.
  8        45             PB13758-RA        176 751 [763, 1531] 3% (too short)  0.0     1.0     100% conserved; 100% extra; 0% missing.
  9        22             GB10071-PA         27 494 [379, 402]  0% (too long)   -7.0    0.0     100% conserved; 100% extra; 0% missing.
 10         0             PB26730-RA          0 Not enough evidence     Not enough evidence     Not enough evidence     Not enough evidence  Not enough evidence

==> Overall Query Score Evaluation:
10 predictions were validated, from which there were:
0 are good prediction(s),
10 are possibly weak prediction(s).
1 prediction was not evaluated due to an insufficient number of BLAST hits.
The median overall score was 64.0 with an upper quartile of 67.0 and a lower quartile of 45.0.
Average running time for LengthCluster Validation: 0.013s per validation
Average running time for LengthRank Validation: 0.0s per validation
Average running time for GeneMerge Validation: 0.001s per validation
Average running time for Duplication Validation: 6.517s per validation
Average running time for MissingExtraSequences Validation: 0.259s per validation

==> GeneValidator output files have been saved to:
    /home/moonhartii/protein_data_2023_06_19_11_28_24
Total running time: 105.422s

**## Do you have another copy of MAFFT / BLAST installed?**

I do, but I didn't change the path to BLAST and MAFFT bin folders in the execution command. I'm thinking that genevalidator does not recognize the code in its file?

(base) moonhartii@LAPTOP-SB1BDPOH:~$ which mafft
/usr/bin/mafft

(base) moonhartii@LAPTOP-SB1BDPOH:~$ which blastp
/home/moonhartii/miniconda3/bin/blastp

(base) moonhartii@LAPTOP-SB1BDPOH:~$ which blastn
/home/moonhartii/genevalidator/bin/blastn

(base) moonhartii@LAPTOP-SB1BDPOH:~$ which tblastn
/home/moonhartii/genevalidator/bin/tblastn

(base) moonhartii@LAPTOP-SB1BDPOH:~$ which tblastx
/home/moonhartii/genevalidator/bin/tblastx


**## What is the output of echo $PATH?**

(base) moonhartii@LAPTOP-SB1BDPOH:~$ echo $PATH
/home/moonhartii/miniconda3/bin:/home/moonhartii/miniconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Program Files (x86)/Common Files/Oracle/Java/javapath:/mnt/c/Program Files (x86)/Intel/iCLS Client:/mnt/c/Program Files/Intel/iCLS Client:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0:/mnt/c/Program Files/Intel/WiFi/bin:/mnt/c/Program Files/Common Files/Intel/WirelessCommon:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/IPT:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/IPT:/mnt/c/WINDOWS/System32/OpenSSH:/mnt/c/Program Files/MEGA-X:/mnt/c/Program Files (x86)/Bitvise SSH Client:/mnt/c/Program Files/Git/cmd:/mnt/c/Program Files/Geneious Prime:/mnt/c/Users/Jamie Acer/AppData/Local/Microsoft/WindowsApps:/snap/bin:/home/moonhartii/maker/bin:/home/moonhartii/maker/exe/augustus/bin:home/moonhartii/miniconda3/share/snap/

**Comment by IsmailM** [comment]
Can you try the following command:

```bash
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin ./genevalidator/genevalidator -db genevalidator/blast_db/swissprot genevalidator/exemplar_data/protein_data.fa
```

**Comment by jwinternitz** [comment]
Still not working...

(base) moonhartii@LAPTOP-SB1BDPOH:~$ PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin ./genevalidator/genevalidator --db genevalidator/blast_db/swissprot genevalidator/exemplar_data/protein_data.fa
==> Analysing input arguments

==> Running BLAST. This may take a while.

==> Extracting fasta sequences for each BLAST HSP from the BLAST database
==> Validating input sequences

 No     Score             Identifier    No_Hits LengthCluster   LengthRank      GeneMerge       Duplication     MissingExtraSequences
  1        67             GB10056-PA         10 339 [317, 365]  40%     -3.5    1.0     100% conserved; 100% extra; 0% missing.
  2        67             GB10063-PA        324 615 [105, 668]  42%     0.0     1.0     100% conserved; 100% extra; 0% missing.
  3        64             GB10113-PA         19 659 [300, 506]  37%     -2.4    0.25    100% conserved; 100% extra; 0% missing.
  4        64          SI2.2.0_02565         18 1761 [1603, 1677]       50%     -0.1    1.0     100% conserved; 100% extra; 0% missing.
  5        67             PB18768-RA          7 132 [124, 137]  43%     0.0     1.0     Not enough evidence
  6        64          SI2.2.0_02651         34 660 [404, 1242] 15% (too short) 0.0     1.0     100% conserved; 100% extra; 0% missing.
  7        45             PB11933-RA         52 845 [667, 885]  37%     1.1     1.0     100% conserved; 100% extra; 0% missing.
  8        45             PB13758-RA        176 751 [763, 1531] 3% (too short)  0.0     1.0     100% conserved; 100% extra; 0% missing.
  9        22             GB10071-PA         27 494 [379, 402]  0% (too long)   -7.0    0.0     100% conserved; 100% extra; 0% missing.
 10         0             PB26730-RA          0 Not enough evidence     Not enough evidence     Not enough evidence     Not enough evidence  Not enough evidence

==> Overall Query Score Evaluation:
10 predictions were validated, from which there were:
0 are good prediction(s),
10 are possibly weak prediction(s).
1 prediction was not evaluated due to an insufficient number of BLAST hits.
The median overall score was 64.0 with an upper quartile of 67.0 and a lower quartile of 45.0.
Average running time for LengthCluster Validation: 0.019s per validation
Average running time for LengthRank Validation: 0.0s per validation
Average running time for GeneMerge Validation: 0.001s per validation
Average running time for Duplication Validation: 6.706s per validation
Average running time for MissingExtraSequences Validation: 0.33s per validation

==> GeneValidator output files have been saved to:
    /home/moonhartii/protein_data_2023_06_19_12_04_18
Total running time: 132.757s

**Comment by misieber** [comment]
I just want to confirm this issue on a different machine.

Running `./genevalidator -d blast_db/swissprot exemplar_data/protein_data.fa` from a clean single line install results in
```
==> Analysing input arguments

==> Running BLAST. This may take a while.

==> Extracting fasta sequences for each BLAST HSP from the BLAST database
==> Validating input sequences

 No	Score	          Identifier	No_Hits	LengthCluster	LengthRank	GeneMerge	Duplication	MissingExtraSequences
  1	   67	          GB10056-PA	     10	339 [317, 365]	40%	-3.5	1.0	100% conserved; 100% extra; 0% missing.
  2	   67	          GB10063-PA	    324	615 [105, 668]	42%	0.0	1.0	100% conserved; 100% extra; 0% missing.
  3	   64	          GB10113-PA	     19	659 [300, 506]	37%	-2.4	0.25	100% conserved; 100% extra; 0% missing.
  4	   64	       SI2.2.0_02565	     18	1761 [1603, 1677]	50%	-0.1	1.0	100% conserved; 100% extra; 0% missing.
  5	   67	          PB18768-RA	      7	132 [124, 137]	43%	0.0	1.0	Not enough evidence
  6	   64	       SI2.2.0_02651	     34	660 [404, 1242]	15% (too short)	0.0	1.0	100% conserved; 100% extra; 0% missing.
  7	   45	          PB11933-RA	     52	845 [667, 885]	37%	1.1	1.0	100% conserved; 100% extra; 0% missing.
  8	   45	          PB13758-RA	    176	751 [763, 1531]	3% (too short)	0.0	1.0	100% conserved; 100% extra; 0% missing.
  9	   22	          GB10071-PA	     27	494 [379, 402]	0% (too long)	-7.0	0.0	100% conserved; 100% extra; 0% missing.
 10	    0	          PB26730-RA	      0	Not enough evidence	Not enough evidence	Not enough evidence	Not enough evidence	Not enough evidence

==> Overall Query Score Evaluation:
10 predictions were validated, from which there were:
0 are good prediction(s),
10 are possibly weak prediction(s).
1 prediction was not evaluated due to an insufficient number of BLAST hits.
The median overall score was 64.0 with an upper quartile of 67.0 and a lower quartile of 45.0.
Average running time for LengthCluster Validation: 0.012s per validation
Average running time for LengthRank Validation: 0.0s per validation
Average running time for GeneMerge Validation: 0.0s per validation
Average running time for Duplication Validation: 9.581s per validation
Average running time for MissingExtraSequences Validation: 0.258s per validation
```

genevalidator version is ``2.1.11``. No other installations of MAFFT/BLAST as far as I can see. 

```
Operating System: Ubuntu 22.04.2 LTS              
Kernel: Linux 5.19.0-43-generic
```

**Comment by IsmailM** [comment]
Hi Jamie,

I managed to reproduce the issue on my end. I have just released a new version of GeneValidator with a fix. I have also added additional checks to avoid such errors popping up again.

Would you mind installing the latest version of GeneValidator using this command and trying again?

```bash
# Install GeneValidator
sh -c "$(curl -fsSL https://raw.githubusercontent.com/wurmlab/genevalidator/master/install.sh)" gv_latest

cd gv_latest

# Run GeneValidator with the exemplar data using the included copy of SwissProt 
./genevalidator -d blast_db/swissprot exemplar_data/protein_data.fa

```

Apologies for the delay in getting this fix sorted.

**Comment by jwinternitz** [comment]
That worked! Thank you so much for getting to the bottom of this. Can you share what the issue was?

**Comment by IsmailM** [comment]
The issue was with extracting the fasta sequence of each Blast hit. As a result, the extracted value was `''` - thus, it was attempting to align ten empty sequences against the original sequence.

Normally, when extracting the fasta sequence for each BLAST hit, the tool attempts three different techniques:

* Firstly, it attempts to use the local internal index - this was failing due to the key having accession version numbers (and the hash not using accession version numbers) 
* Secondly, it attempts to use blastcmd command to extract the sequence from the blast db. This failed due to changes in recent BLAST updates (to do with how the output was written to a temporary file)
* Lastly, it attempts to extract the fasta sequence from NCBI BLAST servers using the eFetch API. 

This was harder to reproduce - as the last step (using eFetch) normally worked. However, in our case, the eFetch API was unable to connect to the BLAST server (due to IP being blocked or the internet connection not fully setup etc.) 

All in all, I ended up fixing each of these procedures, and added additional checks to ensure this doesn't happen again :) All in all, GeneValidator should now be faster by using the internal index.
