### ISSUE TITLE
blastdbcmd '-target_only' argument means that some validations give incorrect answers in BLAST 2.2.28+   

### ISSUE THREAD

**Issue by IsmailM** [wurmlab/GeneValidator#43]
In order to obtain the raw sequence, genevalidator runs the following command:

`"blastdbcmd -target_only -entry '#{accno}' -db '#{db}' -outfmt '%s'"`

This can be found in the  `get_raw_sequences` script and in `sequences.rb#L68`

This works perfectly when running with BLAST 2.2.29+. However, this fails in 2.2.28+, resulting in incorrect results for the alignment validation.

In `BLAST 2.2.28+`, when the genevalidator runs:

- `blastdbcmd -target_only -entry 'P30406' -db 'SwissProt' -outfmt '%s'`
This fails with the response that `Error: Malformatted ID P30406`

However, this passes...
- `blastdbcmd -entry 'P30406' -db 'SwissProt' -outfmt '%s'`

THUS I would like to know if there is any reason why we would want to include the  `-target-only` argument. 

If necessary, we could simply check the version of BLAST in the computer and then run the command that would work with it (or simply ask everyone to upgrade)

**Comment by yeban** [comment]
Let's change minimum BLAST+ version requirement? SequenceServer is calling 2.2.30+.

**Comment by IsmailM** [comment]
minimum BLAST+ version is now 2.2.30+...

So issue is now redundant...
