### ISSUE TITLE
Browser Crashes if 'Show all Plots' button is pressed, when there are a large number of queries

### ISSUE THREAD

**Issue by IsmailM** [wurmlab/genevalidator#55]
Currently, this problem is addressed by limiting this 'show all plots' to only work when fewer than 30 queries.

The problem lies in the fact that a large number of SVGs are rendered all at once on the client side...

I propose that the SVGs should be rendered server side... - i.e. before the results file is created... 

There is a nodeJS way of doing this - look at [this](http://mango-is.com/blog/engineering/pre-render-d3-js-charts-at-server-side.html) and [this gist](https://gist.github.com/mef/7044786)

Any Thoughts

**Comment by yeban** [comment]
An alternative could be to not generate all plots at once but only when they are in the viewport - by tracking scroll position. Updating UI on scroll can be a bit tricky though.

**Comment by yannickwurm** [comment]
we want gem install to be easy - i.e. without adding huge node dependency list...

**Comment by yannickwurm** [comment]
Does this now show an error?

**Comment by IsmailM** [comment]
@yannickwurm 

With the latest GV, if there are more than 30 rows, we do not provide the 'Show all Plots' function. Rather, we show a dismissible [error modal](https://github.com/wurmlab/genevalidator/blob/master/aux/files/js/plots.js#L4) that says that 

`Sorry, this feature is not supported in your browser.`

SO shall we close this issue, or should we leave it open as a low-priority enhancement.

**Comment by yeban** [comment]
This error message is misleading, no? Suggests using another browser will solve the problem? Should say "Too many genes to show all plots at once", or something to that tune.

In the current scheme of things, this solution is appropriate imo. But we will have to think how 'Show all charts' will work in the light of #67. I have proposed a solution for the same in #67 -  I suggest we close this thread and move further discussion to #67.

**Comment by IsmailM** [comment]
The [error message](https://github.com/wurmlab/genevalidator/blob/master/aux/template_footer.erb#L33) is:

```
Oops, Something went wrong!
This operation is not possible. There seems to be too many queries...
```

This is more accurate...

I agree, fixing #67, should potentially fix this...
