### ISSUE TITLE
Unable to open HTML results if results file is too big...

### ISSUE THREAD

**Issue by IsmailM** [wurmlab/genevalidator#67]
When dealing with large data, GV can sometimes produce HTML file that is a few 100mb big (i.e. with 40,000 sequences => 333.9mb file)... (This is despite the fact that I've manually minified the HTML).

Trying to open the file in a browser would result in the browser crashing...

According to a [stackoverflow answer](http://stackoverflow.com/a/12629931?noredirect=1), these are the limitations on the file size on the following browsers...

IE --dies around 35 megs
Firefox --dies around 60 megs
Safari --dies around 60 megs
Chrome --dies around 50 megs

Here are our options:
* Produce the Json (or some kind of DB) so that the HTML file only reads this data as you move into the viewport... (i.e. so as you scroll more rows are added to the table)...
* Don't produce HTML file if it is massive.

**Comment by yeban** [comment]
Chunks of JSON would do. What is the relative importance / timeline for this issue?

**Comment by IsmailM** [comment]
I think we can get away with doing this when the paper is in review...

I started on the fix (using JSON), but will only be able to continue it after my exams (i.e. after mid may)...

**Comment by IsmailM** [comment]
Also, I'm planning on changing the ERB to SLIM so that the HTML is automatically minified...

**Comment by yeban** [comment]
I think you should use one index.html to only load and run JavaScript and do rendering and everything client side. There is no need of an HTML templating engine. If you do take this approach, avoid excessive post-processing of JSON client side though - generate JSON in a way that there's nothing or very little to post-process in the browser. Backbone or Angular or React might be well suited to structuring client side code in this case. (I've zeroed in on React for SequenceServer).

**Comment by IsmailM** [comment]
Thanks @yeban, that makes a lot of sense...

**Comment by yeban** [comment]
I think this one will need careful thought before proceeding with the implementation. If the results are to be lazy loaded on scroll, how will you take care of sorting? Then, the current implementation seems to creates a JSON file for each validation for each sequence. That is, ~500 requests to render 100 sequences (assuming five validations). Will you follow the same scheme or better?

**Comment by IsmailM** [comment]
Have been thinking about this... Here are a few points on the matter

* The `|` delimited console output should be written to file
    * We should delimit by a different character, since most IDs tend to have `|` in them
    * Users would be able to open delimited files in excel or such
* We should provide Json along with the delimited file for power users 
* If we use Json and then try to render the table using the Json on client side, it will still be very difficult. Pagination would be important (it would take ages to 30k+ sequences at once). Moreover, any sorting on the client side would be *fun* (imagine Sorting a Json for 30k+ sequences, using the single threaded Jquery available within the browser)...
* If we go with a local server (i.e. GvApp), we can use a proper database and easily do proper pagination and sorting...

Any thoughts on this??

**Comment by yeban** [comment]
Perhaps `sqlite` can be used. It will complicate the installation (dev headers, build toolchain, going through its/sysadmin if no root access like on clusters). That aside, using a database makes it difficult to _just host_ the results using Apache, for instance by simply dropping the files to `~/Sites` or `~/Public`. I think the ability to easily run & share the results with a group of curators is _extremely_ desirable, and thus database should be used as a last resort.

I would suggest taking inspiration from how JBrowse does things. A `names.json` only containing gene id, total score and score per validation would be less than <1MB for upto 30K entries. This should be loaded entire into memory to render the basic tabular view and used for sorting. Data to render graphs per gene can be chunked into several files, perhaps by id:

```
output/
|- names.json
`- chunks/
    |- 01.json
    `- 02.json
```

Chunking can be done with a very simple hashing scheme:

```
n_genes     = 20000
chunk_size  = 10000
n_chunks    = (n_genes/chunk_size).ceil

crc = crc(gene_id) # gene_id to unique number so we can take mod
chunk_num = crc % n_chunks
```

Using the above pseudocode it can be determine which chunk to write the data to for a gene and which to read from. When the user clicks on 'show graph' button, hash the gene ide using above scheme and just load the corresponding `chunks/xx.json`, look up the data for the given gene id, draw the graphs.

Once a chunk is loaded, you don't have to discard it after getting the data for the gene in question. You could cache the data. Memory consumption can be limited - if a third chunk is loaded, remove the first one. If rendering basic tabular summary of all 30K gene at once is still slow, render only how much will be visible (on scroll, properly debounced).

If you visualise a gene set with evidences in JBrowse for the entire genome, JBrowse overall loads more data than us - in GBs (2.3GB for fire ant) - just that it loads them lazily and discards them when there's too much.

**Comment by yannickwurm** [comment]
In the current implementation, we display some kind of error, correct? I think that is sufficient in the short term: If I want to pull out a table with a subset of scores (e.g. those with <40), I should be able to do that with some creative grepping, right? Other issues are thus of higher importance.

No dbs. Keep things small and simple. Re @yeban's proposal, why chunks - why not one json file per gene?

**Comment by yeban** [comment]
No chunking could also work. Just that with one json file per gene, we may end up generating 20,000 files in a directory. Older and maybe some networked file systems may not handle that many files in a directory properly, and large number of files can make archiving, rsync etc. slower too. Also, it just felt a bit convoluted to me.

On a second thought, one json per file is probably better for us. For each gene we have 'Show plots' button on the right. It would render the plots faster, if data for only that gene has to be loaded. And, pre-loading can be done based on the sort order.

The same hashing scheme can be employed to avoid 20k files in one.

```
crc = crc(gene_id)
chunk_num = crc % n_chunks
FileUtils.mkdir_p chunk_num
File.write(File.join(chunk_num, "#{gene_id}.json"), data)
```

If 20k files in a directory is really a problem. JBrowse's `prepare-refseqs.pl` splits the chunk like above by default, but (iirc) has an option to put all chunks in one directory (~23k files for ~350MB fire ant genome).

**Comment by yeban** [comment]
Clicking on 'Show all charts' could toggle a global flag. On scroll, if this flag is set, load json for that gene and draw the graph.

**Comment by yeban** [comment]
Following @IsmailM 's line of thought in https://github.com/wurmlab/genevalidator/issues/67#issuecomment-104745834:

- CSV / TSV to be viewed and processed further in Excel is a good idea. But that alone won't do. GV's graphs are important, which we can't provide in CSV (as far as I understand). Nor would Excel make a great workflow for genome curation communities. So making it work in browser is important.
- The same JSON we use for client side rendering should be useable as input for applications / scripts / pipelines looking to build on GV's output, or tabular output.
- YAML output should be done with. It can't be used independent of GV: GV class definitions are required to load the YAML, output is likely to change with GV's internals, understanding YAML structure requires understanding GV's class definitions.
- Sorting 30k objects in memory isn't very intensive (try sorting array of 30k elements in Ruby or JS). Sorting 30k DOM nodes is likely a bad thing. Thus requiring a proper model-view separation. When user requests results be sorted by score, GV sorts the array derived from names.json, re-renders the visible portion of the table, renders the rest based on current sort order on scroll.
- If based on scroll proves difficult, paginate the results - 50-100 genes per page.

**Comment by yannickwurm** [comment]
so?

**Comment by IsmailM** [comment]
I'm working on a temporary solution - it isn't the perfect solution but it is better than what we currently have and it isn't too difficult to get it up and running... We can work on the perfect solution after that...

Basically, I'm planning to split large results into smaller files of 5000 rows each... As such, there will only be sorting within files...

The current Alpha produces a JSON file that would be used for streaming/analysing and pipelines/scripts and so I'm not too worried about not being able to sort all input sequences...

I'm hoping to have this done by Monday....

**Comment by yannickwurm** [comment]
Thanks

There's no point to sort in sets of 5000. Its confusing at best.

If that's the solution then its better to disable sorting altogether (above 100?)

++
yannick

**Comment by IsmailM** [comment]
See PR #72 

Thus, once I merge this PR, this issue potentially has working fix...

In terms next steps, this is what I'm planning on doing:

* At the moment, a lot of info (on the approach, explanation, conclusion, and plots) is stored in the output file...
* My initial analysis shows that on large output files, removing this data reduces the output file size by up to 50%...
* Thus I'm planning on creating a single json per row that will contain all this info...
     * At the moment, up to 5 json are created per row; so I will be trying to consolidate them into a single Json file...
* This Json file will then be analysed using JS to obtain this data...

Any thoughts?

**Comment by yeban** [comment]
Are you suggesting to generate an html file with the results table and do the rest (plots, explanation) using JSON?

**Comment by IsmailM** [comment]
Yep, that's exactly what I'm suggesting - a JSON produced for each sequence that contains all the necessary data (i.e. all validation results, explanations & plots data etc.) to produce the results table. In contrast, GV currently produces 5 JSON files per sequence that only contain the plot data. It is hoped that this could be used later to generate the table dynamically.

Moreover, as a significant percentage of the output currently produced by GV is explanation data (stored as data attributes in each cell), it is hoped that this would significantly reduce the size of the output file...

I am hoping to have this ready by tomorrow...

**Comment by IsmailM** [comment]
Hey guys, 

I'm not sure if you've had a chance to look at the alpha PR...

Firstly, in terms of size, the new alpha significantly decreases the size of the index... Rerunning the 5000 sequences that @yeban prevously ran: 

* results.html => 6mb (previously over 22mb)
 
The results are quickly opened in Firefox and chrome... BUT it still is having problems loading in Safari...

PS. my results are available on sm11- `/home/bt11112/5000seqs.tar.gz`

**Comment by yeban** [comment]
This is a very significant improvement. Still, 6MB is probably quite a bit  - we are evaluating on localhost. Not sure if this post claiming Safari's usage to be around 26% is to be trusted, but if it is 10% and above, GV needs to work on Safari - https://blog.shareaholic.com/browser-share-report-05-2014/.

I will wait for another round or two of iteration, if you have them planned, before testing it out myself. Or perhaps you could share the results with use via antgenomes.org/~ismail?

I think you can shave another MB by removing `onclick=addData(...)` from `td`s to a event handler. Roughly:
```
$(document, 'td').click(function (e) {
  var target = $(e.target);
  addData.call(target[0], ...)
});
```
(See jquery event delegation)

Obviously, there's a lot of redundancy in drawing the table itself: same `<td class="danger my-btn-danger" ...` repeated 5000 times and the same `title="Length Cluster` repeated 1000 times on each page, all of which can be rendered client side (and at a time only as many rows as the viewport can accommodate will have to be rendered - thus making for efficient transport and rendering).

Good that 'Show all plots' doesn't crash Firefox. Safari is in general less accommodating though. I won't be surprised if it would have crashed Safari. That is, if the results could have been loaded in Safari to verify. In either case, I'm sure we both understand that 'Show all plots' can't be enabled yet - we are not only concerned about not crashing the browser, but also about providing a fluid user experience. Thus limiting the functionality is better for now.

**Comment by IsmailM** [comment]
I believe we have done as much as we can (without using an external database like mysql etc.)...

Therefore I'm closing this...

Feel free to reopen this if you think there is anything else we can add to this...
