### ISSUE TITLE
-f should be the default and the only option

### ISSUE THREAD

**Issue by yeban** [wurmlab/genevalidator#77]
That is, run blast on all sequences at once.

**Comment by IsmailM** [comment]
Just to add the above

The current default is to run BLAST on each sequence separately and then run GV on it. The benefit of this method is that you start to see the results almost instantly (as it takes less time to run BLAST on a single sequence)...

The alternative, i.e. the `-f, --fast` option runs BLAST on the whole input file producing a BLAST XML file. This BLAST XML file is then used to run GV. The benefit of this method is that this is generally faster (especially with larger input files). However, this means, GV results are not produced instantly - one has to wait for a bit for BLAST to run...

<hr>

Personally, I agree with this issue - `-f` should be the only option...

**Comment by yeban** [comment]
I think that's okay. GV informs user that it's running BLAST, and that's enough. Maybe just say there that it could take a while.

**Comment by yeban** [comment]
Will simplify the code too.

**Comment by IsmailM** [comment]
Yep - agreed...

Will try to get this done today - if not on the 20th...
