### ISSUE TITLE
Drop XML input maybe.

### ISSUE THREAD

**Issue by yeban** [wurmlab/genevalidator#82]
A thought for later. TSV is more flexible - there's access to more data (coverage, taxonomy) that can possibly be used for new validations or to refine existing ones. Will reduce code complexity. Could make it easier to use other alignment program instead of BLAST (I believe TSV output is more common of alignment programs).

**Comment by yannickwurm** [comment]
XML input is helpful because poeple generate XML output for other reasons (e.g. their custom script analysis) & then can simply reuse that output for here.

**Comment by IsmailM** [comment]
I think I agree with @yannickwurm...

Let's keep on supporting both XML and TSV for now...

Thus, I'm closing this now...
